version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: Asia/Kolkata
    groups:
      npm-dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: Asia/Kolkata
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 5
