import assert from 'node:assert/strict';
import test from 'node:test';
import { describeRequests, isInjectedMessage, previewOf, unwrapRequest } from '../src/adapters/preview.js';
import { codexSurface } from '../src/adapters/codex.js';

// The Codex editor extension does not record what you typed. It records what it
// sent, which is your request wrapped in a block about open tabs and the active
// file. Taking that verbatim is what made every session in a folder look alike.
const IDE_WRAPPED = `# Context from my IDE setup:

## Active file: PROFILE_INFORMATION_MAP.md

## Open tabs:
- PROFILE_INFORMATION_MAP.md: PROFILE_INFORMATION_MAP.md

## My request for Codex: good work! now how do you suggest we restructure the directory`;

test('the IDE wrapper is stripped down to the actual request', () => {
  assert.equal(unwrapRequest(IDE_WRAPPED), 'good work! now how do you suggest we restructure the directory');
});

test('a slash command is named by the command, not its caveat', () => {
  const raw =
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>\n' +
    '<command-name>/compact</command-name>\n<command-message>compact</command-message>';
  assert.equal(unwrapRequest(raw), '/compact');
});

test('injected machinery is recognised as such', () => {
  assert.equal(isInjectedMessage('<environment_context>cwd=/x</environment_context>'), true);
  assert.equal(isInjectedMessage('Turn context: something'), true);
  // The Codex editor extension probes for tools whenever it connects.
  assert.equal(
    isInjectedMessage('Check whether the tool load_workspace_dependencies is available in this session.'),
    true
  );
  assert.equal(isInjectedMessage(''), true);
  assert.equal(isInjectedMessage('please refactor the exporter'), false);
});

test('the opening request names a session and the latest one distinguishes it', () => {
  // Two sessions forked from a common parent share the first message exactly,
  // so only the later request can tell them apart.
  const described = describeRequests([
    '<environment_context>ignored</environment_context>',
    'the current root directory has all the information about my background',
    IDE_WRAPPED,
    'okay, add these universities to the US universities document'
  ]);

  assert.equal(described.first, 'the current root directory has all the information about my background');
  assert.equal(described.last, 'okay, add these universities to the US universities document');
});

test('a trailing one-word reply is skipped for something that says what the session is about', () => {
  const described = describeRequests([
    'set up the deployment pipeline for the staging environment',
    'now wire in the smoke tests against the staging URL',
    'yes',
    'continue'
  ]);
  // "continue" is where most conversations end and identifies nothing.
  assert.equal(described.last, 'now wire in the smoke tests against the staging URL');
});

test('a single-message session reports no separate latest', () => {
  const described = describeRequests(['just the one request that is comfortably long enough']);
  assert.equal(described.first, 'just the one request that is comfortably long enough');
  assert.equal(described.last, undefined, 'repeating the same line twice tells the reader nothing');
});

test('a session of pure machinery still gets a label', () => {
  // Better to show the probe than an empty row.
  const described = describeRequests(['Check whether the tool load_workspace_dependencies is available.']);
  assert.match(described.first, /load_workspace_dependencies/);
});

test('previews are flattened to one line and elided', () => {
  assert.equal(previewOf('a\n\n  b   c '), 'a b c');
  const long = previewOf('x'.repeat(200), 40);
  assert.equal(long.length, 40);
  assert.match(long, /…$/);
});

test('a subagent session is named, not rendered as an object', () => {
  // Observed on disk: source is an object for subagent runs, which printed as
  // "[object Object]" in the picker.
  assert.equal(codexSurface({ subagent: { other: 'guardian' } }), 'subagent · guardian');
  assert.equal(codexSurface('vscode'), 'vscode');
  assert.equal(codexSurface(undefined, 'codex_vscode'), 'vscode');
  assert.equal(codexSurface(undefined, undefined), undefined);
});
